### PR TITLE
response.zig -> Response.zig

### PR DESCRIPTION
**Pull request by nektro**
Implements https://github.com/Luukdegram/apple_pie/issues/42#issuecomment-916011235

### CODE REVIEW

**Comment by nektro** [comment]
Checking ` Hide whitespace changes` in the diff settings helps it be a lot easier to look at

**Comment by Luukdegram** [comment]
Thanks but this is no longer needed as Status is now exposed as per #57

**Comment by nektro** [comment]
was this not going to happen anyway so that it would be consistent with `Request.zig` ?

**Comment by Luukdegram** [comment]
I see no reason for that. I just wanted to expose Status for now. Keep in mind that even now the final API is likely to change quite a few more often as I explore ideas. Hence I haven't even tagged a 0.1 yet.

**Pull request closed without merging**
